# The path to store Matrix-related database.
# Must not be shared with any other bots.
data_dir = "./_data"

# The language preferences for outgoing URL preview requests.
crawler_accept_language = "en-US,en;q=0.9"

# (Optional) A web proxy server for URL preview requests.
crawler_proxy = "socks5://127.0.0.1:1080"

# The maximum number of bytes to read for each URL preview request.
crawler_max_size = 10485760

# The User-Agent string for outgoing URL preview requests.
crawler_user_agent = "Mozilla/5.0 (compatible; Matrix-URL-Previewer-Bot; +https://github.com/m13253/matrix-url-previewer-bot; like Discordbot, TelegramBot, Twitterbot)"

# URL rewrite rules.
# Please use https://regex101.com (set to Rust mode) to validate your regex.
#
# These are some popular link preview enhance services as example.
# These free services provide link previews for certain websites that are difficult to crawl.
# However, if you care about privacy, you should host instances of them on your own server.
rewrite_url = [
    ['(?i)^https?://(?:www\.)?b23\.tv/(.*)', "https://b23bb.tv/$1"],
    ['(?i)^https?://(?:www\.)?bilibili\.com/(.*)', "https://bilibilibb.com/$1"],
    ['(?i)^https?://(?:www\.)?bsky\.app/(.*)', "https://fxbsky.app/$1"],
    ['(?i)^https?://(?:www\.)?instagram\.com/(.*)', "https://www.ddinstagram.com/$1"],
    ['(?i)^https?://(?:www\.)?twitter\.com/(.*)', "https://fxtwitter.com/$1"],
    ['(?i)^https?://(?:www\.)?x\.com/(.*)', "https://fixupx.com/$1"],
]
